---
- name: copy zabbix-agent
  copy:
    src: zabbix-agent-3.2.7-1.el7.x86_64.rpm
    dest: /tmp/zabbix-agent-3.2.7-1.el7.x86_64.rpm

- name: install zabbix-agent
  yum:
    name: /tmp/zabbix-agent-3.2.7-1.el7.x86_64.rpm
    state: present

- name: start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted

- name: enable zabbix-agent startup
  shell: systemctl enable zabbix-agent

- name: wait_for
  wait_for:
    delay: 10