---
- name: copy zabbix-agent centos 6 32
  copy:
    src: zabbix-agent-3.2.7-1.el6.i686.rpm
    dest: /tmp/zabbix-agent-3.2.7-1.el6.i686.rpm

- name: install zabbix-agent
  yum:
    name: /tmp/zabbix-agent-3.2.7-1.el6.i686.rpm
    state: present

- name: confige zabbix-agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted

- name: enable zabbix-agent startup
  shell: systemctl enable zabbix-agent