---
- include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_userspace_bits == "64"

- include: centos6_64.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and ansible_userspace_bits == "64"

- include: centos6_32.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and ansible_userspace_bits == "32"